image:
  registry: ghcr.io/zmoog/collector
  tag: latest@sha256:f4a6ed0880a01fa403c13ccba5a88bdda28d21ef7c5d50de0bc306127e85ef36

labels:
  hardware_profile: general-purpose

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

elasticsearch:
  endpoints: ""
  username: ""
  password: ""
  api_key: ""

wavinsentio:
  collection_interval: "1m"
  # Production endpoint.
  endpoint: "https://blaze.wavinsentio.com/wavin.blaze.v1.BlazeDeviceService"
  username: ""
  password: ""
  # This is not a secret, it is the app in Firebase that is used
  # to authenticate with the Wavin Sentio API.
  web_api_key: "AIzaSyBlAtNI7-2jitPul9I-O4EZcT-n0sIay-g"

zcsazzurro:
  collection_interval: "5m"
  things:
    - name: "thing1"
      client_id: ""
      auth_key: ""
      thing_key: ""
    # - name: "thing2"
    #   client_id: ""
    #   auth_key: ""
    #   thing_key: ""

toggl:
  collection_interval: "5m"
  api_token: ""

telemetry:
  log:
    level: debug
